#project language
language: python

#python version
python:
  - "2.6"
  - "2.7"
  - "3.2"

env:
  - DJANGO=1.11.1
  - DJANGO=1.10

# command to install depedencie
install:
  - pip install -q  Django==$DJANGO 
  - pip install -q -r requirement.txt 

# command to run tests
script: python manage.py test hero 